### ISSUE TITLE
API login should not use request body values

### ISSUE THREAD

**Issue by Blahah** [ContentMine/site#161]
When using the API we currently have to include the API key as a key-value pair in the body (json or form). This means the api_key gets stored in the catalogue entry, making it public.

Can we provide it in the headers? `API_KEY` perhaps?

Alternatively, it could be stripped out of the body, but I would argue this is riskier as a mistyped key could still lead to including the api_key in the record.

**Comment by markmacgillivray** [comment]
Ah, this was actually an option in addition to providing the api_key as a request parameter, so that it was outside of request body. However, an error in my code meant that the request params were ignored if body was present. Not hugely useful. I have changed this so that it will look for api_key in request header, request params, and request body now. Also, api_key is ignored if it is found in the request body when saving to the index, so it will not be saved if someone does put it there. It could still end up there if someone puts it under a different key, like apikey or cheesecake.

**Comment by Blahah** [comment]
OK great.

RE: your last point, when I've included `api_key` in the request body, it does get stored, e.g.:

http://contentmine.org/api/catalogue/691b26ae331445d0a9fd817ae0058270

**Comment by markmacgillivray** [comment]
I updated the code and wiped the catalogue again this morning though, so it should not save the api key any more. The link you give is not there any more, was it for an old record before I wiped the index? It should work as expected if you try sending new catalogue entries now.

**Comment by Blahah** [comment]
Yeah it was for an old record - still had the tab open. Thanks, ill reopen if the issue persists.

**Comment by Blahah** [comment]
OK, issue still persists. I'm setting the header `API_KEY`, and getting a 401. Here is the raw header captured during send with the api key redacted:

```
_header: 'POST /api/catalogue HTTP/1.1\r\nAPI_KEY: **********\r\naccept: application/json\r\nuser-agent: request-json/1.0\r\nhost: contentmine.org\r\ncontent-type: application/json\r\ncontent-length: 4223\r\nConnection: keep-alive\r\n\r\n',
```

I tried both 'api_key' and 'API_KEY'.

If I add the key under 'api_key' to the JSON object in the body, authentication works OK.

**Comment by Blahah** [comment]
oh also, node that HTTP header names are case-insensitive, so `API_KEY` and `api_key` are treated the same by the python requests lib. Should only need to check for one of them (seehttp://docs.python-requests.org/en/latest/user/quickstart/#response-headers).

**Comment by markmacgillivray** [comment]
OK I have changed the way headers are checked for, at the top of app.py. It is the same way REMOTE_USER header is checked for now, so it should work if it is there. Try again and let me know.

**Comment by Blahah** [comment]
actually I'm now getting a 500 for any query to the API - see http://contentmine.org/api/

**Comment by markmacgillivray** [comment]
That was due to me losing connection from the train whilst updating the server. Sorry. Should be back up now. (I don't do work on live production servers from trains, but this project is not live production yet :)

**Comment by Blahah** [comment]
No problem at all! OK, 500 is sorted, but the 401 persists when using `api_key` in the header of the request.
